apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          imagePullPolicy: Never
          image: korisnik/vjezba:v5
          ports:
            - containerPort: 8080
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 8080
    nodePort: 30001
  type: NodePort



